ALTER TABLE Users
DROP CONSTRAINT [PK_IdUsername]

ALTER TABLE Users
ADD CONSTRAINT PK_Id PRIMARY KEY (Id)

DELETE FROM Users
    WHERE Username = 'Gosho' 
ALTER TABLE Users
ADD CONSTRAINT UQ_Username UNIQUE(Username)