CREATE TABLE Cities(
CityID INT NOT NULL PRIMARY KEY IDENTITY,
Name NVARCHAR(50) NOT NULL
)

CREATE TABLE Customers(
CustomerID INT NOT NULL PRIMARY KEY IDENTITY,
Name NVARCHAR(50) NOT NULL,
Birthday DATE NOT NULL,
CityID INT FOREIGN KEY REFERENCES Cities(CityID)
)

CREATE TABLE Orders(
OrderID INT NOT NULL PRIMARY KEY IDENTITY,
CustomerID INT FOREIGN KEY REFERENCES Customers(CustomerID)
)

CREATE TABLE ItemTypes(
ItemTypeID INT NOT NULL PRIMARY KEY IDENTITY,
Name NVARCHAR(50) NOT NULL
)

CREATE TABLE Items(
ItemID INT NOT NULL PRIMARY KEY IDENTITY,
Name NVARCHAR(50) NOT NULL,
ItemTypeID INT FOREIGN KEY REFERENCES ItemTypes(ItemTypeID)
)

CREATE TABLE OrderItems(
OrderID INT NOT NULL FOREIGN KEY REFERENCES Orders(OrderID),
ItemID INT NOT NULL FOREIGN KEY REFERENCES Items(ItemID)
)

ALTER TABLE OrderItems
ADD CONSTRAINT PK_OrderItems_Orders_Items PRIMARY KEY(OrderID,ItemID)